### ISSUE TITLE
PostGres server sometimes crashes

### ISSUE THREAD

**Issue by petewarden** [petewarden/dstk#15]
Steps:
Run the DSTK server for several days under load

Result:
The street2coordinates API may stop responding with results, returning an error instead.

Notes:
This seems to be caused by memory allocations problems within the postgres server when dealing with large requests.

Here's the error log from /var/log/postgresql/postgresql-8.4-main.log:

UTC FATAL:  could not create shared memory segment: Cannot allocate memory
UTC DETAIL:  Failed system call was shmget(key=5432001, size=29278208, 03600).
UTC HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory or swap space. To reduce the request size (currently 29278208 bytes), reduce PostgreSQL's shared_buffers parameter (currently 3072) and/or its max_connections parameter (currently 103).
    The PostgreSQL documentation contains more information about shared memory configuration.

**Comment by petewarden** [comment]
I've been investigating this, and it looks like tuning a combination of postgres and kernel shared memory parameters may solve it:
http://www.postgresql.org/docs/8.2/static/kernel-resources.html

**Comment by dogtimemedia** [comment]
There been any movement on this?  I was able to reduce the amount of occurrences by moving to a larger ec2 instance (small, not default micro) but still occurs pretty often.

**Comment by dogtimemedia** [comment]
Looks like this is still using the postgres gem which is no longer maintained.  Switching to the PG gem may alleviate some of these problems.

**Comment by petewarden** [comment]
I've actually checked in some changes to the shared memory setup that seem to have fixed it for the cases I used to be able to reproduce it on. Try a pull of the code if you're running your own copy, or just grab the new AMI at ami-15449d7c in US east on EC2. I don't have a VMware image of it yet unfortunately.

**Comment by apolzon** [comment]
Wow, thanks SO much for creating that new AMI.  Seems to be working fine for me on the micro free tier.

Edit:
The server started throwing errors on every single request after being in constant use (batch encoding) for about 6 hours.  However, the issue may be unrelated to postgres.  The snippet I have (I forgot to grab the logs from the ami before rebooting it):

`ion_passenger/rack/application_spawner.rb:170:in `send'\",
 \"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/rack/application_spawner.rb:170:in `handle_spawn_application'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/utils.rb:479:in `safe_fork'\",
 \"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/rack/application_spawner.rb:165:in `handle_spawn_application'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/abstract_server.rb:357:in `__send__'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/abstract_server.rb:180:in `start'\", 
\"/usr/lib/ruby/gems/1.8/gems/passenger-3.0.4/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'\", 
\"/usr/lib/ruby/gems/1.8/gems/passeng`

I will post a full backtrace if I get it (under a new issue if it is indeed unrelated to postgres)

**Comment by apolzon** [comment]
So it was hard to track down anything useful, (not sure where the application logs are), but I did find a ton of occurrences of: `UTC FATAL:  sorry, too many clients already` in `/var/log/postgresql/postgresql-8.4-main.log`

Attempting to restart the pg_cluster results in the messages posted by the OP.
