### ISSUE TITLE
error on manual setup

### ISSUE THREAD

**Issue by peteyreplies** [petewarden/dstk#45]
Trying to put my own server together and ran into an issue on the first line of the setup txt: 

https://github.com/petewarden/dstk/blob/master/docs/ec2setup.txt

```
~$ sudo apt-add-repository -y ppa:olivier-berten/geo
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner self.run()
File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 99, in run self.add_ppa_signing_key(self.ppa_path)
File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 117, in add_ppa_signing_key  ppa_info = get_ppa_info_from_lp(owner_name, ppa_name)
File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 87, in get_ppa_info_from_lp
return json.loads(lp_page)
File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Not sure if this is my new clean install (12.04 Ubuntu) or the repo but figured I would just flag it for your attention in case expected behavior is different. I'll keep on playing around on my end. I have a dedicated server so it seems silly to run an additional VM inside but I'm more than happy to do it. 

Oh, and dstk is amazing - thank you for your work!

**Comment by peteyreplies** [comment]
hrm, reinstalled ubuntu and it seems to work now.
