### ISSUE TITLE
Unable to pip install dstk

### ISSUE THREAD

**Issue by Chris-Larkin** [petewarden/dstk#65]
Hello, 

I've tried installing dstk using `pip install dstk` but it is returning an error message. I'm running on a virtualenvironment with Python3, and a regular `pip install` returns this error:

```
(py3_base) Chriss-MacBook-Pro:~ chris.larkin$ pip install dstk
Collecting dstk
  Could not find a version that satisfies the requirement dstk (from versions: )
No matching distribution found for dstk
```

I've also tried installing directly from github, but receive this error instead:

```
(py3_base) Chriss-MacBook-Pro:~ chris.larkin$ pip install https://github.com/petewarden/dstk/zipball/master
Collecting https://github.com/petewarden/dstk/zipball/master
  Downloading https://github.com/petewarden/dstk/zipball/master
     / 1.9MB 1.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/chris.larkin/.virtualenvs/py3_base/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
```

I've also tried following the instructions [here](http://www.datasciencetoolkit.org/developerdocs#python) but receive this error when trying to run `python setup.py` from the correct `cd`:

```
Chriss-MacBook-Pro:~ chris.larkin$ workon py3_base
(py3_base) Chriss-MacBook-Pro:~ chris.larkin$ cd "/Users/chris.larkin/.virtualenvs/py3_base/lib/python3.5/site-packages/dstk-0.50"
(py3_base) Chriss-MacBook-Pro:dstk-0.50 chris.larkin$ python setup.py
python: can't open file 'setup.py': [Errno 2] No such file or directory
(py3_base) Chriss-MacBook-Pro:dstk-0.50 chris.larkin$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

I've also tried downloading the tar file directly from PyPi, and placing it in my site-packages folder for the associated virtualenv but that does not work either.

This looks like a fantastic resource and i'd love to use it; any help would be appreciated!

**Comment by lexieheinle** [comment]
Hi,

I had this same problem and fixed it by running 
```python setup.py build ```
```python setup.py install```

**Comment by Sri4464** [comment]
Does this work for python 3.7, I simply cannot download the package using pip due to version conflict

**Comment by ghost** [comment]
The code it is running when you type "python setup.py install" (dstk.py) isn't updated for python 3.  You need to go into the code and put parentheses around all the "print" statements

**Comment by iUnleash** [comment]
Just to follow up on @jds5888 's comment. The module "httplib" has been renamed to "http.client" for python 3. Should already be installed if youre using Anaconda.
